# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windows/ManagerWindowUi.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1112, 799)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.mininetPage = QtWidgets.QWidget()
        self.mininetPage.setObjectName("mininetPage")
        self.stackedWidget.addWidget(self.mininetPage)
        self.hostPage = QtWidgets.QWidget()
        self.hostPage.setObjectName("hostPage")
        self.stackedWidget.addWidget(self.hostPage)
        self.advPage = QtWidgets.QWidget()
        self.advPage.setObjectName("advPage")
        self.stackedWidget.addWidget(self.advPage)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1112, 22))
        self.menubar.setObjectName("menubar")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuCommands = QtWidgets.QMenu(self.menubar)
        self.menuCommands.setObjectName("menuCommands")
        self.menuMininet = QtWidgets.QMenu(self.menuCommands)
        self.menuMininet.setObjectName("menuMininet")
        self.menuHosts = QtWidgets.QMenu(self.menuCommands)
        self.menuHosts.setObjectName("menuHosts")
        self.menuTraffic_replay = QtWidgets.QMenu(self.menubar)
        self.menuTraffic_replay.setObjectName("menuTraffic_replay")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionMininet = QtWidgets.QAction(mainWindow)
        self.actionMininet.setObjectName("actionMininet")
        self.actionHosts = QtWidgets.QAction(mainWindow)
        self.actionHosts.setObjectName("actionHosts")
        self.actionListFiles = QtWidgets.QAction(mainWindow)
        self.actionListFiles.setObjectName("actionListFiles")
        self.actionReplayTraffic = QtWidgets.QAction(mainWindow)
        self.actionReplayTraffic.setObjectName("actionReplayTraffic")
        self.actionTshark = QtWidgets.QAction(mainWindow)
        self.actionTshark.setObjectName("actionTshark")
        self.actionIfconifg = QtWidgets.QAction(mainWindow)
        self.actionIfconifg.setObjectName("actionIfconifg")
        self.actionAdversary = QtWidgets.QAction(mainWindow)
        self.actionAdversary.setObjectName("actionAdversary")
        self.actionCtrl_C = QtWidgets.QAction(mainWindow)
        self.actionCtrl_C.setObjectName("actionCtrl_C")
        self.actionPrepare = QtWidgets.QAction(mainWindow)
        self.actionPrepare.setObjectName("actionPrepare")
        self.actionStart = QtWidgets.QAction(mainWindow)
        self.actionStart.setObjectName("actionStart")
        self.actionStop = QtWidgets.QAction(mainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionPingAll = QtWidgets.QAction(mainWindow)
        self.actionPingAll.setObjectName("actionPingAll")
        self.actionStartXterms = QtWidgets.QAction(mainWindow)
        self.actionStartXterms.setObjectName("actionStartXterms")
        self.actionStopXterms = QtWidgets.QAction(mainWindow)
        self.actionStopXterms.setObjectName("actionStopXterms")
        self.actionInfoDump = QtWidgets.QAction(mainWindow)
        self.actionInfoDump.setObjectName("actionInfoDump")
        self.menuView.addAction(self.actionMininet)
        self.menuView.addAction(self.actionHosts)
        self.menuView.addAction(self.actionAdversary)
        self.menuMininet.addAction(self.actionPingAll)
        self.menuMininet.addAction(self.actionInfoDump)
        self.menuMininet.addAction(self.actionStartXterms)
        self.menuHosts.addAction(self.actionCtrl_C)
        self.menuHosts.addAction(self.actionListFiles)
        self.menuHosts.addAction(self.actionIfconifg)
        self.menuHosts.addAction(self.actionTshark)
        self.menuCommands.addAction(self.menuMininet.menuAction())
        self.menuCommands.addAction(self.menuHosts.menuAction())
        self.menuTraffic_replay.addAction(self.actionPrepare)
        self.menuTraffic_replay.addAction(self.actionStart)
        self.menuTraffic_replay.addAction(self.actionStop)
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuCommands.menuAction())
        self.menubar.addAction(self.menuTraffic_replay.menuAction())

        self.retranslateUi(mainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Emulation Manager"))
        self.menuView.setTitle(_translate("mainWindow", "View"))
        self.menuCommands.setTitle(_translate("mainWindow", "Commands"))
        self.menuMininet.setTitle(_translate("mainWindow", "Mininet"))
        self.menuHosts.setTitle(_translate("mainWindow", "Hosts"))
        self.menuTraffic_replay.setTitle(_translate("mainWindow", "Traffic replay"))
        self.actionMininet.setText(_translate("mainWindow", "Mininet terminal"))
        self.actionHosts.setText(_translate("mainWindow", "Hosts"))
        self.actionListFiles.setText(_translate("mainWindow", "List files"))
        self.actionReplayTraffic.setText(_translate("mainWindow", "Replay traffic"))
        self.actionTshark.setText(_translate("mainWindow", "Tshark"))
        self.actionIfconifg.setText(_translate("mainWindow", "Ifconifg"))
        self.actionAdversary.setText(_translate("mainWindow", "Adversary"))
        self.actionCtrl_C.setText(_translate("mainWindow", "Ctrl + C"))
        self.actionPrepare.setText(_translate("mainWindow", "Prepare"))
        self.actionStart.setText(_translate("mainWindow", "Start"))
        self.actionStop.setText(_translate("mainWindow", "Stop"))
        self.actionPingAll.setText(_translate("mainWindow", "Ping all"))
        self.actionStartXterms.setText(_translate("mainWindow", "Start xterms"))
        self.actionStopXterms.setText(_translate("mainWindow", "Stop xterms"))
        self.actionInfoDump.setText(_translate("mainWindow", "Info dump"))

