# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReplayWindowUi.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TrafficDialog(object):
    def setupUi(self, TrafficDialog):
        TrafficDialog.setObjectName("TrafficDialog")
        TrafficDialog.resize(545, 679)
        self.stackedWidget = QtWidgets.QStackedWidget(TrafficDialog)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 10, 541, 661))
        self.stackedWidget.setObjectName("stackedWidget")
        self.preparePage = QtWidgets.QWidget()
        self.preparePage.setObjectName("preparePage")
        self.predefinedGroup = QtWidgets.QGroupBox(self.preparePage)
        self.predefinedGroup.setEnabled(True)
        self.predefinedGroup.setGeometry(QtCore.QRect(10, 190, 521, 251))
        self.predefinedGroup.setTitle("")
        self.predefinedGroup.setFlat(False)
        self.predefinedGroup.setCheckable(False)
        self.predefinedGroup.setObjectName("predefinedGroup")
        self.startPredefinedlabel = QtWidgets.QLabel(self.predefinedGroup)
        self.startPredefinedlabel.setEnabled(True)
        self.startPredefinedlabel.setGeometry(QtCore.QRect(10, 20, 471, 41))
        self.startPredefinedlabel.setWordWrap(True)
        self.startPredefinedlabel.setObjectName("startPredefinedlabel")
        self.startPredefinedlabel_3 = QtWidgets.QLabel(self.predefinedGroup)
        self.startPredefinedlabel_3.setEnabled(True)
        self.startPredefinedlabel_3.setGeometry(QtCore.QRect(60, 50, 51, 41))
        self.startPredefinedlabel_3.setWordWrap(True)
        self.startPredefinedlabel_3.setObjectName("startPredefinedlabel_3")
        self.comboHost1 = QtWidgets.QComboBox(self.predefinedGroup)
        self.comboHost1.setGeometry(QtCore.QRect(120, 60, 101, 25))
        self.comboHost1.setObjectName("comboHost1")
        self.startPredefinedlabel_4 = QtWidgets.QLabel(self.predefinedGroup)
        self.startPredefinedlabel_4.setEnabled(True)
        self.startPredefinedlabel_4.setGeometry(QtCore.QRect(60, 80, 51, 41))
        self.startPredefinedlabel_4.setWordWrap(True)
        self.startPredefinedlabel_4.setObjectName("startPredefinedlabel_4")
        self.comboHost2 = QtWidgets.QComboBox(self.predefinedGroup)
        self.comboHost2.setGeometry(QtCore.QRect(120, 90, 101, 25))
        self.comboHost2.setObjectName("comboHost2")
        self.addPairButton = QtWidgets.QPushButton(self.predefinedGroup)
        self.addPairButton.setGeometry(QtCore.QRect(90, 130, 89, 25))
        self.addPairButton.setObjectName("addPairButton")
        self.removePairButton = QtWidgets.QPushButton(self.predefinedGroup)
        self.removePairButton.setGeometry(QtCore.QRect(90, 210, 89, 25))
        self.removePairButton.setObjectName("removePairButton")
        self.pairList = QtWidgets.QListWidget(self.predefinedGroup)
        self.pairList.setEnabled(True)
        self.pairList.setGeometry(QtCore.QRect(250, 60, 241, 181))
        self.pairList.setObjectName("pairList")
        self.startPredefinedlabel_5 = QtWidgets.QLabel(self.predefinedGroup)
        self.startPredefinedlabel_5.setEnabled(True)
        self.startPredefinedlabel_5.setGeometry(QtCore.QRect(40, 170, 201, 41))
        self.startPredefinedlabel_5.setWordWrap(True)
        self.startPredefinedlabel_5.setObjectName("startPredefinedlabel_5")
        self.loadGroup = QtWidgets.QGroupBox(self.preparePage)
        self.loadGroup.setEnabled(True)
        self.loadGroup.setGeometry(QtCore.QRect(10, 20, 521, 181))
        self.loadGroup.setTitle("")
        self.loadGroup.setFlat(False)
        self.loadGroup.setCheckable(False)
        self.loadGroup.setObjectName("loadGroup")
        self.loadButton = QtWidgets.QPushButton(self.loadGroup)
        self.loadButton.setGeometry(QtCore.QRect(10, 60, 80, 23))
        self.loadButton.setObjectName("loadButton")
        self.loadLine = QtWidgets.QLineEdit(self.loadGroup)
        self.loadLine.setGeometry(QtCore.QRect(10, 90, 501, 22))
        self.loadLine.setObjectName("loadLine")
        self.startPredefinedlabel_2 = QtWidgets.QLabel(self.loadGroup)
        self.startPredefinedlabel_2.setEnabled(True)
        self.startPredefinedlabel_2.setGeometry(QtCore.QRect(10, 20, 471, 41))
        self.startPredefinedlabel_2.setWordWrap(True)
        self.startPredefinedlabel_2.setObjectName("startPredefinedlabel_2")
        self.splitFlowsButton = QtWidgets.QRadioButton(self.loadGroup)
        self.splitFlowsButton.setGeometry(QtCore.QRect(220, 150, 271, 23))
        self.splitFlowsButton.setCheckable(True)
        self.splitFlowsButton.setChecked(False)
        self.splitFlowsButton.setObjectName("splitFlowsButton")
        self.splitPairsButton = QtWidgets.QRadioButton(self.loadGroup)
        self.splitPairsButton.setGeometry(QtCore.QRect(220, 120, 231, 23))
        self.splitPairsButton.setChecked(True)
        self.splitPairsButton.setObjectName("splitPairsButton")
        self.splitNotButton = QtWidgets.QRadioButton(self.loadGroup)
        self.splitNotButton.setGeometry(QtCore.QRect(30, 120, 141, 23))
        self.splitNotButton.setCheckable(True)
        self.splitNotButton.setChecked(False)
        self.splitNotButton.setObjectName("splitNotButton")
        self.loadGroup_2 = QtWidgets.QGroupBox(self.preparePage)
        self.loadGroup_2.setEnabled(True)
        self.loadGroup_2.setGeometry(QtCore.QRect(10, 430, 521, 171))
        self.loadGroup_2.setTitle("")
        self.loadGroup_2.setFlat(False)
        self.loadGroup_2.setCheckable(False)
        self.loadGroup_2.setObjectName("loadGroup_2")
        self.startPredefinedlabel_10 = QtWidgets.QLabel(self.loadGroup_2)
        self.startPredefinedlabel_10.setEnabled(True)
        self.startPredefinedlabel_10.setGeometry(QtCore.QRect(10, 20, 471, 41))
        self.startPredefinedlabel_10.setWordWrap(True)
        self.startPredefinedlabel_10.setObjectName("startPredefinedlabel_10")
        self.clusterKmeansButton = QtWidgets.QCheckBox(self.loadGroup_2)
        self.clusterKmeansButton.setGeometry(QtCore.QRect(60, 70, 112, 23))
        self.clusterKmeansButton.setObjectName("clusterKmeansButton")
        self.clusterDBSCANButton = QtWidgets.QCheckBox(self.loadGroup_2)
        self.clusterDBSCANButton.setGeometry(QtCore.QRect(60, 100, 112, 23))
        self.clusterDBSCANButton.setObjectName("clusterDBSCANButton")
        self.clusterAffinityButton = QtWidgets.QCheckBox(self.loadGroup_2)
        self.clusterAffinityButton.setGeometry(QtCore.QRect(60, 130, 171, 23))
        self.clusterAffinityButton.setObjectName("clusterAffinityButton")
        self.clusterSpectralButton = QtWidgets.QCheckBox(self.loadGroup_2)
        self.clusterSpectralButton.setGeometry(QtCore.QRect(300, 70, 161, 23))
        self.clusterSpectralButton.setObjectName("clusterSpectralButton")
        self.clusterOPTICSButton = QtWidgets.QCheckBox(self.loadGroup_2)
        self.clusterOPTICSButton.setGeometry(QtCore.QRect(300, 100, 112, 23))
        self.clusterOPTICSButton.setObjectName("clusterOPTICSButton")
        self.clusterBirchButton = QtWidgets.QCheckBox(self.loadGroup_2)
        self.clusterBirchButton.setGeometry(QtCore.QRect(300, 130, 112, 23))
        self.clusterBirchButton.setObjectName("clusterBirchButton")
        self.prepareButtonBox = QtWidgets.QDialogButtonBox(self.preparePage)
        self.prepareButtonBox.setGeometry(QtCore.QRect(10, 630, 511, 25))
        self.prepareButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.prepareButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.prepareButtonBox.setObjectName("prepareButtonBox")
        self.line = QtWidgets.QFrame(self.preparePage)
        self.line.setGeometry(QtCore.QRect(10, 610, 521, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.preparePage)
        self.label.setGeometry(QtCore.QRect(16, 0, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.preparePage)
        self.clusteringPage = QtWidgets.QWidget()
        self.clusteringPage.setObjectName("clusteringPage")
        self.label_3 = QtWidgets.QLabel(self.clusteringPage)
        self.label_3.setGeometry(QtCore.QRect(16, 0, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.clusteringPage)
        self.label_4.setGeometry(QtCore.QRect(16, 41, 511, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.loadGroup_3 = QtWidgets.QGroupBox(self.clusteringPage)
        self.loadGroup_3.setEnabled(True)
        self.loadGroup_3.setGeometry(QtCore.QRect(10, 100, 521, 131))
        self.loadGroup_3.setTitle("")
        self.loadGroup_3.setFlat(False)
        self.loadGroup_3.setCheckable(False)
        self.loadGroup_3.setObjectName("loadGroup_3")
        self.label_7 = QtWidgets.QLabel(self.loadGroup_3)
        self.label_7.setEnabled(True)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 471, 41))
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.pathLabel = QtWidgets.QLabel(self.loadGroup_3)
        self.pathLabel.setEnabled(True)
        self.pathLabel.setGeometry(QtCore.QRect(30, 50, 471, 41))
        self.pathLabel.setWordWrap(True)
        self.pathLabel.setObjectName("pathLabel")
        self.loadFilesLabel = QtWidgets.QLabel(self.loadGroup_3)
        self.loadFilesLabel.setEnabled(True)
        self.loadFilesLabel.setGeometry(QtCore.QRect(10, 90, 241, 41))
        self.loadFilesLabel.setWordWrap(True)
        self.loadFilesLabel.setObjectName("loadFilesLabel")
        self.splitLabel = QtWidgets.QLabel(self.loadGroup_3)
        self.splitLabel.setEnabled(True)
        self.splitLabel.setGeometry(QtCore.QRect(270, 90, 241, 41))
        self.splitLabel.setWordWrap(True)
        self.splitLabel.setObjectName("splitLabel")
        self.loadGroup_4 = QtWidgets.QGroupBox(self.clusteringPage)
        self.loadGroup_4.setEnabled(True)
        self.loadGroup_4.setGeometry(QtCore.QRect(10, 230, 521, 91))
        self.loadGroup_4.setTitle("")
        self.loadGroup_4.setFlat(False)
        self.loadGroup_4.setCheckable(False)
        self.loadGroup_4.setObjectName("loadGroup_4")
        self.featureStatusLabel = QtWidgets.QLabel(self.loadGroup_4)
        self.featureStatusLabel.setEnabled(True)
        self.featureStatusLabel.setGeometry(QtCore.QRect(10, 20, 501, 41))
        self.featureStatusLabel.setWordWrap(True)
        self.featureStatusLabel.setObjectName("featureStatusLabel")
        self.featureTimeLabel = QtWidgets.QLabel(self.loadGroup_4)
        self.featureTimeLabel.setEnabled(True)
        self.featureTimeLabel.setGeometry(QtCore.QRect(10, 50, 471, 41))
        self.featureTimeLabel.setWordWrap(True)
        self.featureTimeLabel.setObjectName("featureTimeLabel")
        self.loadGroup_5 = QtWidgets.QGroupBox(self.clusteringPage)
        self.loadGroup_5.setEnabled(True)
        self.loadGroup_5.setGeometry(QtCore.QRect(10, 320, 521, 201))
        self.loadGroup_5.setTitle("")
        self.loadGroup_5.setFlat(False)
        self.loadGroup_5.setCheckable(False)
        self.loadGroup_5.setObjectName("loadGroup_5")
        self.clusteringStatusLabel = QtWidgets.QLabel(self.loadGroup_5)
        self.clusteringStatusLabel.setEnabled(True)
        self.clusteringStatusLabel.setGeometry(QtCore.QRect(10, 20, 471, 41))
        self.clusteringStatusLabel.setWordWrap(True)
        self.clusteringStatusLabel.setObjectName("clusteringStatusLabel")
        self.label_6 = QtWidgets.QLabel(self.loadGroup_5)
        self.label_6.setEnabled(True)
        self.label_6.setGeometry(QtCore.QRect(10, 50, 471, 31))
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.clusteringTimeLabel = QtWidgets.QLabel(self.loadGroup_5)
        self.clusteringTimeLabel.setEnabled(True)
        self.clusteringTimeLabel.setGeometry(QtCore.QRect(30, 80, 471, 101))
        self.clusteringTimeLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.clusteringTimeLabel.setWordWrap(True)
        self.clusteringTimeLabel.setObjectName("clusteringTimeLabel")
        self.statusLabel = QtWidgets.QLabel(self.clusteringPage)
        self.statusLabel.setGeometry(QtCore.QRect(10, 540, 511, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.statusLabel.setFont(font)
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.line_2 = QtWidgets.QFrame(self.clusteringPage)
        self.line_2.setGeometry(QtCore.QRect(10, 610, 521, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.clusteringButtonBox = QtWidgets.QDialogButtonBox(self.clusteringPage)
        self.clusteringButtonBox.setGeometry(QtCore.QRect(10, 630, 511, 25))
        self.clusteringButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.clusteringButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.clusteringButtonBox.setObjectName("clusteringButtonBox")
        self.stackedWidget.addWidget(self.clusteringPage)
        self.resultsPage = QtWidgets.QWidget()
        self.resultsPage.setObjectName("resultsPage")
        self.label_2 = QtWidgets.QLabel(self.resultsPage)
        self.label_2.setGeometry(QtCore.QRect(16, 0, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.resultsPage)
        self.label_5.setGeometry(QtCore.QRect(16, 41, 511, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.line_3 = QtWidgets.QFrame(self.resultsPage)
        self.line_3.setGeometry(QtCore.QRect(10, 610, 521, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.resultsButtonBox = QtWidgets.QDialogButtonBox(self.resultsPage)
        self.resultsButtonBox.setGeometry(QtCore.QRect(10, 630, 511, 25))
        self.resultsButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.resultsButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Retry)
        self.resultsButtonBox.setObjectName("resultsButtonBox")
        self.stackedTables = QtWidgets.QStackedWidget(self.resultsPage)
        self.stackedTables.setGeometry(QtCore.QRect(10, 160, 521, 431))
        self.stackedTables.setObjectName("stackedTables")
        self.label_8 = QtWidgets.QLabel(self.resultsPage)
        self.label_8.setGeometry(QtCore.QRect(30, 120, 151, 17))
        self.label_8.setObjectName("label_8")
        self.comboClustering = QtWidgets.QComboBox(self.resultsPage)
        self.comboClustering.setGeometry(QtCore.QRect(190, 114, 241, 31))
        self.comboClustering.setObjectName("comboClustering")
        self.stackedWidget.addWidget(self.resultsPage)

        self.retranslateUi(TrafficDialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TrafficDialog)

    def retranslateUi(self, TrafficDialog):
        _translate = QtCore.QCoreApplication.translate
        TrafficDialog.setWindowTitle(_translate("TrafficDialog", "Traffic Replay"))
        self.startPredefinedlabel.setText(_translate("TrafficDialog", "Choose pairs of hosts, between which traffic will be replayed"))
        self.startPredefinedlabel_3.setText(_translate("TrafficDialog", "Host 1:"))
        self.startPredefinedlabel_4.setText(_translate("TrafficDialog", "Host 2:"))
        self.addPairButton.setText(_translate("TrafficDialog", "Add"))
        self.removePairButton.setText(_translate("TrafficDialog", "Remove"))
        self.startPredefinedlabel_5.setText(_translate("TrafficDialog", "Remove pair selected on list"))
        self.loadButton.setText(_translate("TrafficDialog", "Load"))
        self.startPredefinedlabel_2.setText(_translate("TrafficDialog", "Choose folder containing \".pcap\" files to be replayed"))
        self.splitFlowsButton.setText(_translate("TrafficDialog", "split files due to IP and ports (flows)"))
        self.splitPairsButton.setText(_translate("TrafficDialog", "split files due to IP (host pairs)"))
        self.splitNotButton.setText(_translate("TrafficDialog", "do not split files"))
        self.startPredefinedlabel_10.setText(_translate("TrafficDialog", "Choose clustering algorithm for grouping \".pcap\" files"))
        self.clusterKmeansButton.setText(_translate("TrafficDialog", "K-means"))
        self.clusterDBSCANButton.setText(_translate("TrafficDialog", "DBSCAN"))
        self.clusterAffinityButton.setText(_translate("TrafficDialog", "Affinity propagation"))
        self.clusterSpectralButton.setText(_translate("TrafficDialog", "Spectral clustering"))
        self.clusterOPTICSButton.setText(_translate("TrafficDialog", "OPTICS"))
        self.clusterBirchButton.setText(_translate("TrafficDialog", "Birch"))
        self.label.setText(_translate("TrafficDialog", "Traffic replay"))
        self.label_3.setText(_translate("TrafficDialog", "Traffic replay"))
        self.label_4.setText(_translate("TrafficDialog", "Preparation"))
        self.label_7.setText(_translate("TrafficDialog", "Choosen directory with \".pcap\" files:"))
        self.pathLabel.setText(_translate("TrafficDialog", "path"))
        self.loadFilesLabel.setText(_translate("TrafficDialog", "Number of files found:"))
        self.splitLabel.setText(_translate("TrafficDialog", "Split files: "))
        self.featureStatusLabel.setText(_translate("TrafficDialog", "Feature extraction"))
        self.featureTimeLabel.setText(_translate("TrafficDialog", "Time: -"))
        self.clusteringStatusLabel.setText(_translate("TrafficDialog", "Clustering"))
        self.label_6.setText(_translate("TrafficDialog", "Time:"))
        self.clusteringTimeLabel.setText(_translate("TrafficDialog", "-"))
        self.statusLabel.setText(_translate("TrafficDialog", "Please wait ..."))
        self.label_2.setText(_translate("TrafficDialog", "Traffic replay"))
        self.label_5.setText(_translate("TrafficDialog", "Results"))
        self.label_8.setText(_translate("TrafficDialog", "Clustering algorithm:"))

