# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windows/WizardWindowUi.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Wizard(object):
    def setupUi(self, Wizard):
        Wizard.setObjectName("Wizard")
        Wizard.resize(819, 611)
        self.wizardIntroduction = QtWidgets.QWizardPage()
        self.wizardIntroduction.setObjectName("wizardIntroduction")
        self.generalArea_3 = QtWidgets.QScrollArea(self.wizardIntroduction)
        self.generalArea_3.setGeometry(QtCore.QRect(260, 260, 521, 281))
        self.generalArea_3.setWidgetResizable(True)
        self.generalArea_3.setObjectName("generalArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 519, 279))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.generalLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.generalLabel.setGeometry(QtCore.QRect(20, 30, 481, 101))
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.generalLabel.setFont(font)
        self.generalLabel.setObjectName("generalLabel")
        self.predefinedGroup_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.predefinedGroup_3.setEnabled(True)
        self.predefinedGroup_3.setGeometry(QtCore.QRect(10, 170, 481, 91))
        self.predefinedGroup_3.setTitle("")
        self.predefinedGroup_3.setFlat(False)
        self.predefinedGroup_3.setCheckable(False)
        self.predefinedGroup_3.setObjectName("predefinedGroup_3")
        self.predefinedDescription_3 = QtWidgets.QLabel(self.predefinedGroup_3)
        self.predefinedDescription_3.setEnabled(True)
        self.predefinedDescription_3.setGeometry(QtCore.QRect(0, 20, 481, 71))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.predefinedDescription_3.setFont(font)
        self.predefinedDescription_3.setAlignment(QtCore.Qt.AlignCenter)
        self.predefinedDescription_3.setObjectName("predefinedDescription_3")
        self.generalArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.generalLabel_2 = QtWidgets.QLabel(self.wizardIntroduction)
        self.generalLabel_2.setGeometry(QtCore.QRect(260, 20, 521, 101))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(19)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.generalLabel_2.setFont(font)
        self.generalLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.generalLabel_2.setObjectName("generalLabel_2")
        self.generalLabel_8 = QtWidgets.QLabel(self.wizardIntroduction)
        self.generalLabel_8.setGeometry(QtCore.QRect(260, 140, 521, 101))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(19)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.generalLabel_8.setFont(font)
        self.generalLabel_8.setAlignment(QtCore.Qt.AlignCenter)
        self.generalLabel_8.setObjectName("generalLabel_8")
        self.line_3 = QtWidgets.QFrame(self.wizardIntroduction)
        self.line_3.setGeometry(QtCore.QRect(260, 120, 521, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.frameBanner = QtWidgets.QFrame(self.wizardIntroduction)
        self.frameBanner.setGeometry(QtCore.QRect(20, 20, 201, 521))
        self.frameBanner.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frameBanner.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBanner.setObjectName("frameBanner")
        self.labelBannerSDN = QtWidgets.QLabel(self.frameBanner)
        self.labelBannerSDN.setGeometry(QtCore.QRect(20, 50, 146, 321))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(83)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.labelBannerSDN.setFont(font)
        self.labelBannerSDN.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelBannerSDN.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelBannerSDN.setTextFormat(QtCore.Qt.AutoText)
        self.labelBannerSDN.setScaledContents(False)
        self.labelBannerSDN.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelBannerSDN.setObjectName("labelBannerSDN")
        self.labelBannerTestbed = QtWidgets.QLabel(self.frameBanner)
        self.labelBannerTestbed.setGeometry(QtCore.QRect(10, 340, 181, 174))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(47)
        font.setBold(True)
        font.setWeight(75)
        self.labelBannerTestbed.setFont(font)
        self.labelBannerTestbed.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBannerTestbed.setObjectName("labelBannerTestbed")
        Wizard.addPage(self.wizardIntroduction)
        self.wizardStart = QtWidgets.QWizardPage()
        self.wizardStart.setObjectName("wizardStart")
        self.generalArea = QtWidgets.QScrollArea(self.wizardStart)
        self.generalArea.setGeometry(QtCore.QRect(260, 60, 521, 481))
        self.generalArea.setWidgetResizable(True)
        self.generalArea.setObjectName("generalArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 519, 479))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.loadRadio = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.loadRadio.setGeometry(QtCore.QRect(10, 10, 211, 21))
        self.loadRadio.setObjectName("loadRadio")
        self.customRadio = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.customRadio.setGeometry(QtCore.QRect(10, 310, 341, 21))
        self.customRadio.setObjectName("customRadio")
        self.loadGroup = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.loadGroup.setEnabled(True)
        self.loadGroup.setGeometry(QtCore.QRect(20, 20, 491, 91))
        self.loadGroup.setTitle("")
        self.loadGroup.setFlat(False)
        self.loadGroup.setCheckable(False)
        self.loadGroup.setObjectName("loadGroup")
        self.loadButton = QtWidgets.QPushButton(self.loadGroup)
        self.loadButton.setGeometry(QtCore.QRect(10, 30, 80, 23))
        self.loadButton.setObjectName("loadButton")
        self.loadLine = QtWidgets.QLineEdit(self.loadGroup)
        self.loadLine.setGeometry(QtCore.QRect(10, 60, 471, 22))
        self.loadLine.setObjectName("loadLine")
        self.predefinedRadio = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.predefinedRadio.setGeometry(QtCore.QRect(10, 130, 281, 21))
        self.predefinedRadio.setObjectName("predefinedRadio")
        self.predefinedGroup = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.predefinedGroup.setEnabled(True)
        self.predefinedGroup.setGeometry(QtCore.QRect(20, 140, 491, 161))
        self.predefinedGroup.setTitle("")
        self.predefinedGroup.setFlat(False)
        self.predefinedGroup.setCheckable(False)
        self.predefinedGroup.setObjectName("predefinedGroup")
        self.predefinedList = QtWidgets.QListWidget(self.predefinedGroup)
        self.predefinedList.setEnabled(True)
        self.predefinedList.setGeometry(QtCore.QRect(10, 30, 471, 71))
        self.predefinedList.setObjectName("predefinedList")
        self.startPredefinedlabel = QtWidgets.QLabel(self.predefinedGroup)
        self.startPredefinedlabel.setEnabled(True)
        self.startPredefinedlabel.setGeometry(QtCore.QRect(10, 110, 471, 41))
        self.startPredefinedlabel.setWordWrap(True)
        self.startPredefinedlabel.setObjectName("startPredefinedlabel")
        self.customGroup = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.customGroup.setGeometry(QtCore.QRect(20, 320, 491, 141))
        self.customGroup.setTitle("")
        self.customGroup.setObjectName("customGroup")
        self.customCombo = QtWidgets.QComboBox(self.customGroup)
        self.customCombo.setGeometry(QtCore.QRect(10, 30, 171, 25))
        self.customCombo.setObjectName("customCombo")
        self.customCombo.addItem("")
        self.customCombo.addItem("")
        self.customCombo.addItem("")
        self.stackedCustom = QtWidgets.QStackedWidget(self.customGroup)
        self.stackedCustom.setGeometry(QtCore.QRect(-10, 60, 491, 71))
        self.stackedCustom.setObjectName("stackedCustom")
        self.linearPage = QtWidgets.QWidget()
        self.linearPage.setObjectName("linearPage")
        self.linearLabel1 = QtWidgets.QLabel(self.linearPage)
        self.linearLabel1.setGeometry(QtCore.QRect(20, 10, 201, 25))
        self.linearLabel1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.linearLabel1.setObjectName("linearLabel1")
        self.linearLine1 = QtWidgets.QLineEdit(self.linearPage)
        self.linearLine1.setGeometry(QtCore.QRect(230, 10, 140, 25))
        self.linearLine1.setObjectName("linearLine1")
        self.linearLabel2 = QtWidgets.QLabel(self.linearPage)
        self.linearLabel2.setGeometry(QtCore.QRect(20, 40, 201, 25))
        self.linearLabel2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.linearLabel2.setObjectName("linearLabel2")
        self.linearLine2 = QtWidgets.QLineEdit(self.linearPage)
        self.linearLine2.setGeometry(QtCore.QRect(230, 40, 140, 25))
        self.linearLine2.setObjectName("linearLine2")
        self.stackedCustom.addWidget(self.linearPage)
        self.treePage = QtWidgets.QWidget()
        self.treePage.setObjectName("treePage")
        self.treeLine2 = QtWidgets.QLineEdit(self.treePage)
        self.treeLine2.setGeometry(QtCore.QRect(230, 40, 140, 25))
        self.treeLine2.setObjectName("treeLine2")
        self.linearLabel2_2 = QtWidgets.QLabel(self.treePage)
        self.linearLabel2_2.setGeometry(QtCore.QRect(30, 40, 191, 25))
        self.linearLabel2_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.linearLabel2_2.setObjectName("linearLabel2_2")
        self.linearLabel1_3 = QtWidgets.QLabel(self.treePage)
        self.linearLabel1_3.setGeometry(QtCore.QRect(30, 10, 191, 25))
        self.linearLabel1_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.linearLabel1_3.setObjectName("linearLabel1_3")
        self.treeLine1 = QtWidgets.QLineEdit(self.treePage)
        self.treeLine1.setGeometry(QtCore.QRect(230, 10, 140, 25))
        self.treeLine1.setObjectName("treeLine1")
        self.stackedCustom.addWidget(self.treePage)
        self.torusPage = QtWidgets.QWidget()
        self.torusPage.setObjectName("torusPage")
        self.linearLabel2_3 = QtWidgets.QLabel(self.torusPage)
        self.linearLabel2_3.setGeometry(QtCore.QRect(30, 40, 191, 25))
        self.linearLabel2_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.linearLabel2_3.setObjectName("linearLabel2_3")
        self.torusLine3 = QtWidgets.QLineEdit(self.torusPage)
        self.torusLine3.setGeometry(QtCore.QRect(230, 40, 140, 25))
        self.torusLine3.setObjectName("torusLine3")
        self.torusLine1 = QtWidgets.QLineEdit(self.torusPage)
        self.torusLine1.setGeometry(QtCore.QRect(140, 10, 91, 25))
        self.torusLine1.setObjectName("torusLine1")
        self.torusLine2 = QtWidgets.QLineEdit(self.torusPage)
        self.torusLine2.setGeometry(QtCore.QRect(360, 10, 91, 25))
        self.torusLine2.setText("")
        self.torusLine2.setObjectName("torusLine2")
        self.linearLabel1_2 = QtWidgets.QLabel(self.torusPage)
        self.linearLabel1_2.setGeometry(QtCore.QRect(20, 10, 111, 25))
        self.linearLabel1_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.linearLabel1_2.setObjectName("linearLabel1_2")
        self.linearLabel1_4 = QtWidgets.QLabel(self.torusPage)
        self.linearLabel1_4.setGeometry(QtCore.QRect(240, 10, 111, 25))
        self.linearLabel1_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.linearLabel1_4.setObjectName("linearLabel1_4")
        self.stackedCustom.addWidget(self.torusPage)
        self.generalArea.setWidget(self.scrollAreaWidgetContents)
        self.generalLabel_3 = QtWidgets.QLabel(self.wizardStart)
        self.generalLabel_3.setGeometry(QtCore.QRect(260, 20, 530, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.generalLabel_3.setFont(font)
        self.generalLabel_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.generalLabel_3.setObjectName("generalLabel_3")
        self.frameBanner_2 = QtWidgets.QFrame(self.wizardStart)
        self.frameBanner_2.setGeometry(QtCore.QRect(20, 20, 201, 521))
        self.frameBanner_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frameBanner_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBanner_2.setObjectName("frameBanner_2")
        self.labelBannerSDN_2 = QtWidgets.QLabel(self.frameBanner_2)
        self.labelBannerSDN_2.setGeometry(QtCore.QRect(20, 50, 146, 321))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(83)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.labelBannerSDN_2.setFont(font)
        self.labelBannerSDN_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelBannerSDN_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelBannerSDN_2.setTextFormat(QtCore.Qt.AutoText)
        self.labelBannerSDN_2.setScaledContents(False)
        self.labelBannerSDN_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelBannerSDN_2.setObjectName("labelBannerSDN_2")
        self.labelBannerTestbed_2 = QtWidgets.QLabel(self.frameBanner_2)
        self.labelBannerTestbed_2.setGeometry(QtCore.QRect(10, 340, 181, 174))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(47)
        font.setBold(True)
        font.setWeight(75)
        self.labelBannerTestbed_2.setFont(font)
        self.labelBannerTestbed_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBannerTestbed_2.setObjectName("labelBannerTestbed_2")
        Wizard.addPage(self.wizardStart)
        self.wizardLoad = QtWidgets.QWizardPage()
        self.wizardLoad.setObjectName("wizardLoad")
        self.generalLabel_4 = QtWidgets.QLabel(self.wizardLoad)
        self.generalLabel_4.setGeometry(QtCore.QRect(260, 20, 530, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.generalLabel_4.setFont(font)
        self.generalLabel_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.generalLabel_4.setObjectName("generalLabel_4")
        self.generalArea_2 = QtWidgets.QScrollArea(self.wizardLoad)
        self.generalArea_2.setGeometry(QtCore.QRect(260, 60, 521, 481))
        self.generalArea_2.setWidgetResizable(True)
        self.generalArea_2.setObjectName("generalArea_2")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 519, 479))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.loadGroup_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_5)
        self.loadGroup_2.setEnabled(True)
        self.loadGroup_2.setGeometry(QtCore.QRect(20, 20, 491, 101))
        self.loadGroup_2.setTitle("")
        self.loadGroup_2.setFlat(False)
        self.loadGroup_2.setCheckable(False)
        self.loadGroup_2.setObjectName("loadGroup_2")
        self.loadPathLabel = QtWidgets.QLabel(self.loadGroup_2)
        self.loadPathLabel.setGeometry(QtCore.QRect(10, 20, 471, 81))
        self.loadPathLabel.setObjectName("loadPathLabel")
        self.predefinedGroup_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_5)
        self.predefinedGroup_2.setEnabled(True)
        self.predefinedGroup_2.setGeometry(QtCore.QRect(20, 150, 491, 191))
        self.predefinedGroup_2.setTitle("")
        self.predefinedGroup_2.setFlat(False)
        self.predefinedGroup_2.setCheckable(False)
        self.predefinedGroup_2.setObjectName("predefinedGroup_2")
        self.predefinedDescription_2 = QtWidgets.QLabel(self.predefinedGroup_2)
        self.predefinedDescription_2.setEnabled(True)
        self.predefinedDescription_2.setGeometry(QtCore.QRect(10, 100, 471, 51))
        self.predefinedDescription_2.setText("")
        self.predefinedDescription_2.setObjectName("predefinedDescription_2")
        self.loadToposLabel = QtWidgets.QLabel(self.predefinedGroup_2)
        self.loadToposLabel.setGeometry(QtCore.QRect(10, 50, 471, 141))
        self.loadToposLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.loadToposLabel.setObjectName("loadToposLabel")
        self.loadNumberLabel = QtWidgets.QLabel(self.predefinedGroup_2)
        self.loadNumberLabel.setGeometry(QtCore.QRect(10, 30, 231, 17))
        self.loadNumberLabel.setObjectName("loadNumberLabel")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 241, 21))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label.setGeometry(QtCore.QRect(10, 5, 81, 31))
        self.label.setObjectName("label")
        self.loadResultLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.loadResultLabel.setGeometry(QtCore.QRect(10, 390, 501, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.loadResultLabel.setFont(font)
        self.loadResultLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.loadResultLabel.setObjectName("loadResultLabel")
        self.generalArea_2.setWidget(self.scrollAreaWidgetContents_5)
        self.frameBanner_3 = QtWidgets.QFrame(self.wizardLoad)
        self.frameBanner_3.setGeometry(QtCore.QRect(20, 20, 201, 521))
        self.frameBanner_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frameBanner_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBanner_3.setObjectName("frameBanner_3")
        self.labelBannerSDN_3 = QtWidgets.QLabel(self.frameBanner_3)
        self.labelBannerSDN_3.setGeometry(QtCore.QRect(20, 50, 146, 321))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(83)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.labelBannerSDN_3.setFont(font)
        self.labelBannerSDN_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelBannerSDN_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelBannerSDN_3.setTextFormat(QtCore.Qt.AutoText)
        self.labelBannerSDN_3.setScaledContents(False)
        self.labelBannerSDN_3.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelBannerSDN_3.setObjectName("labelBannerSDN_3")
        self.labelBannerTestbed_3 = QtWidgets.QLabel(self.frameBanner_3)
        self.labelBannerTestbed_3.setGeometry(QtCore.QRect(10, 340, 181, 174))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(47)
        font.setBold(True)
        font.setWeight(75)
        self.labelBannerTestbed_3.setFont(font)
        self.labelBannerTestbed_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBannerTestbed_3.setObjectName("labelBannerTestbed_3")
        Wizard.addPage(self.wizardLoad)
        self.wizardPredefined = QtWidgets.QWizardPage()
        self.wizardPredefined.setObjectName("wizardPredefined")
        self.generalLabel_5 = QtWidgets.QLabel(self.wizardPredefined)
        self.generalLabel_5.setGeometry(QtCore.QRect(260, 20, 530, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.generalLabel_5.setFont(font)
        self.generalLabel_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.generalLabel_5.setObjectName("generalLabel_5")
        self.frameBanner_4 = QtWidgets.QFrame(self.wizardPredefined)
        self.frameBanner_4.setGeometry(QtCore.QRect(20, 20, 201, 521))
        self.frameBanner_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frameBanner_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBanner_4.setObjectName("frameBanner_4")
        self.labelBannerSDN_4 = QtWidgets.QLabel(self.frameBanner_4)
        self.labelBannerSDN_4.setGeometry(QtCore.QRect(20, 50, 146, 321))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(83)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.labelBannerSDN_4.setFont(font)
        self.labelBannerSDN_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelBannerSDN_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelBannerSDN_4.setTextFormat(QtCore.Qt.AutoText)
        self.labelBannerSDN_4.setScaledContents(False)
        self.labelBannerSDN_4.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelBannerSDN_4.setObjectName("labelBannerSDN_4")
        self.labelBannerTestbed_4 = QtWidgets.QLabel(self.frameBanner_4)
        self.labelBannerTestbed_4.setGeometry(QtCore.QRect(10, 340, 181, 174))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(47)
        font.setBold(True)
        font.setWeight(75)
        self.labelBannerTestbed_4.setFont(font)
        self.labelBannerTestbed_4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBannerTestbed_4.setObjectName("labelBannerTestbed_4")
        self.generalArea_4 = QtWidgets.QScrollArea(self.wizardPredefined)
        self.generalArea_4.setGeometry(QtCore.QRect(260, 60, 521, 481))
        self.generalArea_4.setWidgetResizable(True)
        self.generalArea_4.setObjectName("generalArea_4")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 519, 479))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.loadGroup_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_6)
        self.loadGroup_3.setEnabled(True)
        self.loadGroup_3.setGeometry(QtCore.QRect(20, 20, 491, 101))
        self.loadGroup_3.setTitle("")
        self.loadGroup_3.setFlat(False)
        self.loadGroup_3.setCheckable(False)
        self.loadGroup_3.setObjectName("loadGroup_3")
        self.predefinedPathLabel = QtWidgets.QLabel(self.loadGroup_3)
        self.predefinedPathLabel.setGeometry(QtCore.QRect(10, 20, 471, 81))
        self.predefinedPathLabel.setObjectName("predefinedPathLabel")
        self.predefinedGroup_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_6)
        self.predefinedGroup_4.setEnabled(True)
        self.predefinedGroup_4.setGeometry(QtCore.QRect(20, 150, 491, 191))
        self.predefinedGroup_4.setTitle("")
        self.predefinedGroup_4.setFlat(False)
        self.predefinedGroup_4.setCheckable(False)
        self.predefinedGroup_4.setObjectName("predefinedGroup_4")
        self.predefinedDescription_4 = QtWidgets.QLabel(self.predefinedGroup_4)
        self.predefinedDescription_4.setEnabled(True)
        self.predefinedDescription_4.setGeometry(QtCore.QRect(10, 100, 471, 51))
        self.predefinedDescription_4.setText("")
        self.predefinedDescription_4.setObjectName("predefinedDescription_4")
        self.scrollArea = QtWidgets.QScrollArea(self.predefinedGroup_4)
        self.scrollArea.setGeometry(QtCore.QRect(10, 30, 471, 151))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 469, 149))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_7)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.predefinedTopoLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.predefinedTopoLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.predefinedTopoLabel.setObjectName("predefinedTopoLabel")
        self.verticalLayout_9.addWidget(self.predefinedTopoLabel)
        self.verticalLayout_13.addLayout(self.verticalLayout_9)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_7)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 241, 21))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_2.setGeometry(QtCore.QRect(10, 5, 111, 31))
        self.label_2.setObjectName("label_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents_6)
        self.scrollArea_2.setGeometry(QtCore.QRect(20, 350, 501, 121))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_9 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_9.setGeometry(QtCore.QRect(0, 0, 499, 119))
        self.scrollAreaWidgetContents_9.setObjectName("scrollAreaWidgetContents_9")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_9)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.predefinedDescriptionLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_9)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.predefinedDescriptionLabel.setFont(font)
        self.predefinedDescriptionLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.predefinedDescriptionLabel.setWordWrap(True)
        self.predefinedDescriptionLabel.setObjectName("predefinedDescriptionLabel")
        self.verticalLayout_11.addWidget(self.predefinedDescriptionLabel)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_9)
        self.generalArea_4.setWidget(self.scrollAreaWidgetContents_6)
        Wizard.addPage(self.wizardPredefined)
        self.wizardCustom = QtWidgets.QWizardPage()
        self.wizardCustom.setObjectName("wizardCustom")
        self.topologyArea = QtWidgets.QScrollArea(self.wizardCustom)
        self.topologyArea.setGeometry(QtCore.QRect(260, 60, 521, 481))
        self.topologyArea.setWidgetResizable(True)
        self.topologyArea.setObjectName("topologyArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 519, 479))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ipBaseLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.ipBaseLabel.setObjectName("ipBaseLabel")
        self.horizontalLayout_2.addWidget(self.ipBaseLabel)
        self.ipBaseLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.ipBaseLine.setObjectName("ipBaseLine")
        self.horizontalLayout_2.addWidget(self.ipBaseLine)
        self.ipSlashLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ipSlashLabel.setFont(font)
        self.ipSlashLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ipSlashLabel.setObjectName("ipSlashLabel")
        self.horizontalLayout_2.addWidget(self.ipSlashLabel)
        self.ipMaskLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.ipMaskLine.setObjectName("ipMaskLine")
        self.horizontalLayout_2.addWidget(self.ipMaskLine)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.line_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_3.addWidget(self.line_7)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.natBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.natBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.natBox.setObjectName("natBox")
        self.verticalLayout_3.addWidget(self.natBox, 0, QtCore.Qt.AlignRight)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.imageLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.imageLabel.setObjectName("imageLabel")
        self.horizontalLayout_4.addWidget(self.imageLabel)
        self.imageLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.imageLine.setObjectName("imageLine")
        self.horizontalLayout_4.addWidget(self.imageLine)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_3.addWidget(self.line_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.portLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.portLabel.setObjectName("portLabel")
        self.verticalLayout.addWidget(self.portLabel, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.hostPortLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.hostPortLabel.setObjectName("hostPortLabel")
        self.horizontalLayout_5.addWidget(self.hostPortLabel)
        self.hostPortLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.hostPortLine.setObjectName("hostPortLine")
        self.horizontalLayout_5.addWidget(self.hostPortLine)
        self.machinePortLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.machinePortLabel.setObjectName("machinePortLabel")
        self.horizontalLayout_5.addWidget(self.machinePortLabel)
        self.machinePortLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.machinePortLine.setObjectName("machinePortLine")
        self.horizontalLayout_5.addWidget(self.machinePortLine)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_3.addWidget(self.line_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.directoryLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.directoryLabel.setObjectName("directoryLabel")
        self.verticalLayout_2.addWidget(self.directoryLabel, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.machinePathLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.machinePathLabel.setObjectName("machinePathLabel")
        self.verticalLayout_4.addWidget(self.machinePathLabel)
        self.machinePathLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.machinePathLine.setObjectName("machinePathLine")
        self.verticalLayout_4.addWidget(self.machinePathLine)
        self.hostPathLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.hostPathLabel.setObjectName("hostPathLabel")
        self.verticalLayout_4.addWidget(self.hostPathLabel)
        self.hostPathLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.hostPathLine.setObjectName("hostPathLine")
        self.verticalLayout_4.addWidget(self.hostPathLine)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_3.addWidget(self.line_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.delayLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.delayLabel.setObjectName("delayLabel")
        self.horizontalLayout_8.addWidget(self.delayLabel)
        self.delayLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.delayLine.setObjectName("delayLine")
        self.horizontalLayout_8.addWidget(self.delayLine)
        self.secondsLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.secondsLabel.setObjectName("secondsLabel")
        self.horizontalLayout_8.addWidget(self.secondsLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.bandwithLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.bandwithLabel.setObjectName("bandwithLabel")
        self.horizontalLayout_7.addWidget(self.bandwithLabel)
        self.bandwithLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.bandwithLine.setObjectName("bandwithLine")
        self.horizontalLayout_7.addWidget(self.bandwithLine)
        self.bitsLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.bitsLabel.setObjectName("bitsLabel")
        self.horizontalLayout_7.addWidget(self.bitsLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.topologyArea.setWidget(self.scrollAreaWidgetContents_2)
        self.generalLabel_6 = QtWidgets.QLabel(self.wizardCustom)
        self.generalLabel_6.setGeometry(QtCore.QRect(260, 20, 530, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.generalLabel_6.setFont(font)
        self.generalLabel_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.generalLabel_6.setObjectName("generalLabel_6")
        self.frameBanner_5 = QtWidgets.QFrame(self.wizardCustom)
        self.frameBanner_5.setGeometry(QtCore.QRect(20, 20, 201, 521))
        self.frameBanner_5.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frameBanner_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBanner_5.setObjectName("frameBanner_5")
        self.labelBannerSDN_5 = QtWidgets.QLabel(self.frameBanner_5)
        self.labelBannerSDN_5.setGeometry(QtCore.QRect(20, 50, 146, 321))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(83)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.labelBannerSDN_5.setFont(font)
        self.labelBannerSDN_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelBannerSDN_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelBannerSDN_5.setTextFormat(QtCore.Qt.AutoText)
        self.labelBannerSDN_5.setScaledContents(False)
        self.labelBannerSDN_5.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelBannerSDN_5.setObjectName("labelBannerSDN_5")
        self.labelBannerTestbed_5 = QtWidgets.QLabel(self.frameBanner_5)
        self.labelBannerTestbed_5.setGeometry(QtCore.QRect(10, 340, 181, 174))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(47)
        font.setBold(True)
        font.setWeight(75)
        self.labelBannerTestbed_5.setFont(font)
        self.labelBannerTestbed_5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBannerTestbed_5.setObjectName("labelBannerTestbed_5")
        Wizard.addPage(self.wizardCustom)
        self.wizardController = QtWidgets.QWizardPage()
        self.wizardController.setObjectName("wizardController")
        self.controllerArea = QtWidgets.QScrollArea(self.wizardController)
        self.controllerArea.setGeometry(QtCore.QRect(260, 60, 521, 461))
        self.controllerArea.setWidgetResizable(True)
        self.controllerArea.setObjectName("controllerArea")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 519, 459))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.localRadio = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_4)
        self.localRadio.setObjectName("localRadio")
        self.verticalLayout_5.addWidget(self.localRadio)
        self.floodlightRadio = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_4)
        self.floodlightRadio.setObjectName("floodlightRadio")
        self.verticalLayout_5.addWidget(self.floodlightRadio)
        self.floodlightGroup = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.floodlightGroup.setTitle("")
        self.floodlightGroup.setFlat(False)
        self.floodlightGroup.setCheckable(False)
        self.floodlightGroup.setObjectName("floodlightGroup")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.floodlightGroup)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.dockerNameLabel = QtWidgets.QLabel(self.floodlightGroup)
        self.dockerNameLabel.setObjectName("dockerNameLabel")
        self.horizontalLayout_10.addWidget(self.dockerNameLabel)
        self.dockerNameLine = QtWidgets.QLineEdit(self.floodlightGroup)
        self.dockerNameLine.setObjectName("dockerNameLine")
        self.horizontalLayout_10.addWidget(self.dockerNameLine)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.line = QtWidgets.QFrame(self.floodlightGroup)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.floodlightPortLabel = QtWidgets.QLabel(self.floodlightGroup)
        self.floodlightPortLabel.setObjectName("floodlightPortLabel")
        self.verticalLayout_6.addWidget(self.floodlightPortLabel, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.dockerSwitchLabel = QtWidgets.QLabel(self.floodlightGroup)
        self.dockerSwitchLabel.setObjectName("dockerSwitchLabel")
        self.horizontalLayout_13.addWidget(self.dockerSwitchLabel)
        self.dockerSwitchLine = QtWidgets.QLineEdit(self.floodlightGroup)
        self.dockerSwitchLine.setObjectName("dockerSwitchLine")
        self.horizontalLayout_13.addWidget(self.dockerSwitchLine)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.dockerWebLabel = QtWidgets.QLabel(self.floodlightGroup)
        self.dockerWebLabel.setObjectName("dockerWebLabel")
        self.horizontalLayout_9.addWidget(self.dockerWebLabel)
        self.dockerWebLine = QtWidgets.QLineEdit(self.floodlightGroup)
        self.dockerWebLine.setObjectName("dockerWebLine")
        self.horizontalLayout_9.addWidget(self.dockerWebLine)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_5.addWidget(self.floodlightGroup)
        self.remoteRadio = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_4)
        self.remoteRadio.setObjectName("remoteRadio")
        self.verticalLayout_5.addWidget(self.remoteRadio)
        self.remoteGroup = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.remoteGroup.setTitle("")
        self.remoteGroup.setObjectName("remoteGroup")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.remoteGroup)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.controllerIpLabel = QtWidgets.QLabel(self.remoteGroup)
        self.controllerIpLabel.setObjectName("controllerIpLabel")
        self.horizontalLayout_12.addWidget(self.controllerIpLabel)
        self.controllerIpLine = QtWidgets.QLineEdit(self.remoteGroup)
        self.controllerIpLine.setObjectName("controllerIpLine")
        self.horizontalLayout_12.addWidget(self.controllerIpLine)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.controllerPortLabel = QtWidgets.QLabel(self.remoteGroup)
        self.controllerPortLabel.setObjectName("controllerPortLabel")
        self.horizontalLayout_11.addWidget(self.controllerPortLabel)
        self.controllerPortLine = QtWidgets.QLineEdit(self.remoteGroup)
        self.controllerPortLine.setObjectName("controllerPortLine")
        self.horizontalLayout_11.addWidget(self.controllerPortLine)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.verticalLayout_5.addWidget(self.remoteGroup)
        self.controllerArea.setWidget(self.scrollAreaWidgetContents_4)
        self.generalLabel_7 = QtWidgets.QLabel(self.wizardController)
        self.generalLabel_7.setGeometry(QtCore.QRect(260, 20, 530, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.generalLabel_7.setFont(font)
        self.generalLabel_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.generalLabel_7.setObjectName("generalLabel_7")
        self.frameBanner_7 = QtWidgets.QFrame(self.wizardController)
        self.frameBanner_7.setGeometry(QtCore.QRect(20, 20, 201, 521))
        self.frameBanner_7.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frameBanner_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBanner_7.setObjectName("frameBanner_7")
        self.labelBannerSDN_6 = QtWidgets.QLabel(self.frameBanner_7)
        self.labelBannerSDN_6.setGeometry(QtCore.QRect(20, 50, 146, 321))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(83)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.labelBannerSDN_6.setFont(font)
        self.labelBannerSDN_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelBannerSDN_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelBannerSDN_6.setTextFormat(QtCore.Qt.AutoText)
        self.labelBannerSDN_6.setScaledContents(False)
        self.labelBannerSDN_6.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelBannerSDN_6.setObjectName("labelBannerSDN_6")
        self.labelBannerTestbed_7 = QtWidgets.QLabel(self.frameBanner_7)
        self.labelBannerTestbed_7.setGeometry(QtCore.QRect(10, 340, 181, 174))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(47)
        font.setBold(True)
        font.setWeight(75)
        self.labelBannerTestbed_7.setFont(font)
        self.labelBannerTestbed_7.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBannerTestbed_7.setObjectName("labelBannerTestbed_7")
        Wizard.addPage(self.wizardController)
        self.wizardFinish = QtWidgets.QWizardPage()
        self.wizardFinish.setObjectName("wizardFinish")
        self.generalLabel_9 = QtWidgets.QLabel(self.wizardFinish)
        self.generalLabel_9.setGeometry(QtCore.QRect(250, 80, 521, 151))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(19)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.generalLabel_9.setFont(font)
        self.generalLabel_9.setAlignment(QtCore.Qt.AlignCenter)
        self.generalLabel_9.setObjectName("generalLabel_9")
        self.generalLabel_10 = QtWidgets.QLabel(self.wizardFinish)
        self.generalLabel_10.setGeometry(QtCore.QRect(260, 240, 521, 151))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(19)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.generalLabel_10.setFont(font)
        self.generalLabel_10.setAlignment(QtCore.Qt.AlignCenter)
        self.generalLabel_10.setObjectName("generalLabel_10")
        self.frameBanner_6 = QtWidgets.QFrame(self.wizardFinish)
        self.frameBanner_6.setGeometry(QtCore.QRect(20, 20, 201, 521))
        self.frameBanner_6.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frameBanner_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBanner_6.setObjectName("frameBanner_6")
        self.labelBannerSDN_7 = QtWidgets.QLabel(self.frameBanner_6)
        self.labelBannerSDN_7.setGeometry(QtCore.QRect(20, 50, 146, 321))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(83)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.labelBannerSDN_7.setFont(font)
        self.labelBannerSDN_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelBannerSDN_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelBannerSDN_7.setTextFormat(QtCore.Qt.AutoText)
        self.labelBannerSDN_7.setScaledContents(False)
        self.labelBannerSDN_7.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelBannerSDN_7.setObjectName("labelBannerSDN_7")
        self.labelBannerTestbed_8 = QtWidgets.QLabel(self.frameBanner_6)
        self.labelBannerTestbed_8.setGeometry(QtCore.QRect(10, 340, 181, 174))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(47)
        font.setBold(True)
        font.setWeight(75)
        self.labelBannerTestbed_8.setFont(font)
        self.labelBannerTestbed_8.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBannerTestbed_8.setObjectName("labelBannerTestbed_8")
        Wizard.addPage(self.wizardFinish)

        self.retranslateUi(Wizard)
        self.stackedCustom.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Wizard)

    def retranslateUi(self, Wizard):
        _translate = QtCore.QCoreApplication.translate
        Wizard.setWindowTitle(_translate("Wizard", "Wizard"))
        self.generalLabel.setText(_translate("Wizard", "Autor / author:\n"
"     Przemysław Wojsław\n"
"Opiekun pracy / thesis supervisor: \n"
"     dr hab. inż. Mariusz Rawski, prof. PW"))
        self.predefinedDescription_3.setText(_translate("Wizard", "Created for Master\'s Thesis on Warsaw Uniwersity of Technology\n"
"Warsaw, 2021"))
        self.generalLabel_2.setText(_translate("Wizard", "Realistyczne odtwarzanie\n"
"wielopunktowego ruchu sieciowego\n"
"na potrzeby badań sieci SDN"))
        self.generalLabel_8.setText(_translate("Wizard", "Realistic replay\n"
"of multipoint network traffic\n"
"for SDN network research"))
        self.labelBannerSDN.setText(_translate("Wizard", "S\n"
"D\n"
"N"))
        self.labelBannerTestbed.setText(_translate("Wizard", "Testbed"))
        self.loadRadio.setText(_translate("Wizard", "Load from file"))
        self.customRadio.setText(_translate("Wizard", "Create custom configuration"))
        self.loadButton.setText(_translate("Wizard", "Load"))
        self.predefinedRadio.setText(_translate("Wizard", "Use predefined topology"))
        self.startPredefinedlabel.setText(_translate("Wizard", "To learn more about predefined topologies or to create your own check the \"tools/predeifinedTopos.py\" and \"topo/predefined/\"."))
        self.customCombo.setItemText(0, _translate("Wizard", "Linear"))
        self.customCombo.setItemText(1, _translate("Wizard", "Tree"))
        self.customCombo.setItemText(2, _translate("Wizard", "Torus"))
        self.linearLabel1.setText(_translate("Wizard", "Number of switches:"))
        self.linearLabel2.setText(_translate("Wizard", "Number of hosts per switch:"))
        self.linearLabel2_2.setText(_translate("Wizard", "Fanout:"))
        self.linearLabel1_3.setText(_translate("Wizard", "Depth of the tree:"))
        self.linearLabel2_3.setText(_translate("Wizard", "Number of hosts per switch:"))
        self.linearLabel1_2.setText(_translate("Wizard", "Dimension in x:"))
        self.linearLabel1_4.setText(_translate("Wizard", "Dimension in y:"))
        self.generalLabel_3.setText(_translate("Wizard", "Choose topology creation method:"))
        self.labelBannerSDN_2.setText(_translate("Wizard", "S\n"
"D\n"
"N"))
        self.labelBannerTestbed_2.setText(_translate("Wizard", "Testbed"))
        self.generalLabel_4.setText(_translate("Wizard", "Chosen file analysis"))
        self.loadPathLabel.setText(_translate("Wizard", "path"))
        self.loadToposLabel.setText(_translate("Wizard", "topos"))
        self.loadNumberLabel.setText(_translate("Wizard", "Number of topologies: "))
        self.label_3.setText(_translate("Wizard", "Constructor dictionary - \"topos\":"))
        self.label.setText(_translate("Wizard", "File path:"))
        self.loadResultLabel.setText(_translate("Wizard", "Goood"))
        self.labelBannerSDN_3.setText(_translate("Wizard", "S\n"
"D\n"
"N"))
        self.labelBannerTestbed_3.setText(_translate("Wizard", "Testbed"))
        self.generalLabel_5.setText(_translate("Wizard", "Predefined topology description"))
        self.labelBannerSDN_4.setText(_translate("Wizard", "S\n"
"D\n"
"N"))
        self.labelBannerTestbed_4.setText(_translate("Wizard", "Testbed"))
        self.predefinedPathLabel.setText(_translate("Wizard", "path"))
        self.predefinedTopoLabel.setText(_translate("Wizard", "topos"))
        self.label_4.setText(_translate("Wizard", "Topology:"))
        self.label_2.setText(_translate("Wizard", "Chosen preset:"))
        self.predefinedDescriptionLabel.setText(_translate("Wizard", "Goood"))
        self.ipBaseLabel.setText(_translate("Wizard", "IP base:"))
        self.ipSlashLabel.setText(_translate("Wizard", "/"))
        self.label_5.setText(_translate("Wizard", "Gateway (IP *.*.*.1) connected to first switch"))
        self.natBox.setText(_translate("Wizard", "Network Adress Translation (NAT), required for Internet access:  "))
        self.imageLabel.setText(_translate("Wizard", "Docker image for hosts:"))
        self.portLabel.setText(_translate("Wizard", "Port forwarding (for every host, incrementing by 1)"))
        self.hostPortLabel.setText(_translate("Wizard", "First host port: "))
        self.machinePortLabel.setText(_translate("Wizard", "Machine port:"))
        self.directoryLabel.setText(_translate("Wizard", "Shared directory (volume)"))
        self.machinePathLabel.setText(_translate("Wizard", "Path on machine"))
        self.hostPathLabel.setText(_translate("Wizard", "Path on host: "))
        self.delayLabel.setText(_translate("Wizard", "Delay on links: "))
        self.secondsLabel.setText(_translate("Wizard", " ms "))
        self.bandwithLabel.setText(_translate("Wizard", "Bandwidth of links: "))
        self.bitsLabel.setText(_translate("Wizard", " Mbit/s "))
        self.generalLabel_6.setText(_translate("Wizard", "Enter topology parameters"))
        self.labelBannerSDN_5.setText(_translate("Wizard", "S\n"
"D\n"
"N"))
        self.labelBannerTestbed_5.setText(_translate("Wizard", "Testbed"))
        self.localRadio.setText(_translate("Wizard", "Use local Mininet controller"))
        self.floodlightRadio.setText(_translate("Wizard", "Use local Floodlight controller in Docker container"))
        self.dockerNameLabel.setText(_translate("Wizard", "Name for container:"))
        self.floodlightPortLabel.setText(_translate("Wizard", "Port mapping"))
        self.dockerSwitchLabel.setText(_translate("Wizard", "Map Floodlight control port 6653 to Docker container port:"))
        self.dockerWebLabel.setText(_translate("Wizard", "Map Floodlight web GUI port 8080 to Docker container port:"))
        self.remoteRadio.setText(_translate("Wizard", "Use remote controller"))
        self.controllerIpLabel.setText(_translate("Wizard", "IP adress: "))
        self.controllerPortLabel.setText(_translate("Wizard", "Port: "))
        self.generalLabel_7.setText(_translate("Wizard", "Select SDN controller"))
        self.labelBannerSDN_6.setText(_translate("Wizard", "S\n"
"D\n"
"N"))
        self.labelBannerTestbed_7.setText(_translate("Wizard", "Testbed"))
        self.generalLabel_9.setText(_translate("Wizard", "Press \"Finish\" button\n"
"to start preparing emulation"))
        self.generalLabel_10.setText(_translate("Wizard", "In a few seconds new window will open,\n"
" allowing to manage your network."))
        self.labelBannerSDN_7.setText(_translate("Wizard", "S\n"
"D\n"
"N"))
        self.labelBannerTestbed_8.setText(_translate("Wizard", "Testbed"))

